# Site settings
description: Stuff of interest to me and perhaps others
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.arwhyte.org"
# url: "http://localhost:3000" # the base hostname & protocol for your site

# User settings
username: arwhyte
user_description: Anthony Whyte
user_title: Anthony Whyte
email: anth@arwhyte.org
twitter_username: arwhyte
github_username:  arwhyte
gplus_username:  anthwhyte
disqus_username: arwhyte

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
